name: sample_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.24.4' #The version of Flutter used in this project.

dependencies:
  flutter:
    sdk: flutter

  # A
  analyzer: any
  auto_route: any  # A powerful routing library, supports features like nested routes and route guards.
  animation_list: ^3.1.0

  # C
  cupertino_icons: ^1.0.8  # A set of iOS-style icons for Flutter apps on iOS.
  curl_logger_dio_interceptor: ^1.0.0  # Logs Dio HTTP requests in a cURL-like format for easier debugging.
  cached_network_image: ^3.4.1
  csv: ^6.0.0

  # D
  dartz: ^0.10.1  # Provides functional data types like Either and Option in Dart.
  dio: ^5.7.0  # A powerful HTTP client library for Flutter, with support for interceptors, global configuration, and retry logic.
  dotted_border: ^2.1.0
  device_preview:

  # E
  easy_localization: ^3.0.7  # A localization library that makes it easy to handle internationalization in Flutter apps.
  equatable: ^2.0.5

  # F
  flutter_svg: ^2.0.10+1
  flutter_screenutil: ^5.9.3  # Supports responsive design for multiple screen sizes.
  freezed_annotation: any  # Annotation support for the Freezed package to create immutable and sealed classes.
  flutter_secure_storage: ^9.2.2 #Flutter Secure Storage provides API to store data in secure storage.
  flutter_slidable: ^3.1.2
  flutter_hooks: ^0.21.2
  flutter_riverpod: ^2.6.1

  # G
  gap: ^3.0.1  # Provides spacing between widgets in Flutter layouts.
  google_fonts: ^6.2.1
  google_nav_bar: ^5.0.7
  extension_google_sign_in_as_googleapis_auth: ^2.0.12
  googleapis: ^13.2.0

  # H
  highlight_text: ^1.8.0
  hooks_riverpod: ^2.0.0

  # I
  intl: ^0.19.0  # Provides internationalization features like number formatting, date/time formatting, and translations.
  image_picker: ^1.1.2
  isar_key_value: ^0.3.0
  isar: any

  # J
  json_annotation: ^4.9.0  # Annotations to help with serializing/deserializing JSON in Dart.

  # L
  logger: ^2.4.0  # A lightweight logging library for Flutter and Dart, with support for multiple log outputs.
  line_icons: ^2.0.3
  loading_animation_widget: ^1.3.0

  # M
  mobile_scanner: 6.0.6

  # P
  pretty_dio_logger: ^1.4.0  # A Dio plugin for logging requests/responses in a more readable format.
  pin_code_fields: ^8.0.1
  permission_handler: ^11.3.1
  package_info_plus: ^8.1.0
  path_provider: ^2.1.5

  # S
  smooth_page_indicator: ^1.2.0+3
  shared_preferences: ^2.3.2
  screenshot: ^3.0.0
  share_plus: ^10.1.4
  sign_in_button: ^3.0.0

  # U
  url_launcher: ^6.3.1
  uuid: ^4.5.1

  # R
  retrofit: ^4.4.1  # A library that simplifies making RESTful HTTP requests using code generation and annotations.
  # https://medium.com/mindful-engineering/retrofit-the-easiest-way-to-call-rest-apis-is-flutter-fe55d1e7c5c2
  riverpod: ^2.6.1
  riverpod_annotation: any

  # T
  toastification: ^2.3.0

  # W

dev_dependencies:
  flutter_test:
    sdk: flutter

  # B
  build_runner: ^2.4.13  # A build system for Dart projects, allowing you to run code generation and other build tasks.

  # F
  freezed: ^2.5.2 # A package that simplifies the creation of immutable classes and unions/sealed classes in Dart.

  # I
  injectable_generator: ^2.4.2  # A code generator for injectable that simplifies dependency injection in Dart applications.
  isar_generator: any

  # J
#  json_serializable: ^6.8.0  # A code generator that simplifies JSON serialization/deserialization in Dart.

  # R
  auto_route_generator: ^8.0.0  # A code generator for the auto_route package to simplify route management.
#  retrofit_generator: ^9.1.2  # A code generator for Retrofit, facilitating the creation of RESTful API clients.
  riverpod_generator: ^2.4.0
  # L
  flutter_lints: ^5.0.0  # A set of recommended lints for Flutter projects to improve code quality and maintainability.

  # F
  flutter_launcher_icons: ^0.14.2
flutter:
  uses-material-design: true

  assets:
    - assets/config/
    - assets/translations/
    - assets/translations/en-US.json
